# Recovered from the pre-truncation .pyc.
# Each entry: (check name, source variable, needle[, needle2...])
SOURCE_GUARDS = [
    ('questing/', 'm', '.lua in TOC', 'modules\\questing\\', 'm', '.lua', 'toc'),
    ('questing modules load before Suite', 'toc', 'modules\\questing\\QuestLog.lua'),
    ('Navigator.lua in TOC', 'core\\Navigator.lua', 'toc'),
    ('ChatHandler ships /raijin nav', 'cmd == "nav"', 'chathandler'),
    ('core/', 'm', '.lua in TOC', 'core\\', 'm', '.lua', 'toc'),
    ('Scheduler + Pathfinder load before Navigator', 'toc', 'core\\Scheduler.lua'),
    ('Events starts the frame-budget scheduler', 'Scheduler.start', 'events'),
    ('Pathfinder routes ground queries through the shared cache', 'GroundCache', 'pathfinder_src'),
    ('no Executor._human state table', 'Executor._human', 'executor'),
    ('no reaction_until in Executor', 'reaction_until', 'executor'),
    ('no attempts_since_skip in Executor', 'attempts_since_skip', 'executor'),
    ('no C_Timer.After defer in Executor cast path', 'C_Timer.After', 'executor'),
    ('no stale _human poke in ChatHandler', '_human', 'chathandler'),
    ('ChatHandler resets throttle for diagnostic', '_last_attempt_t = 0', 'chathandler'),
    ('Executor uses authoritative _gcd_until gate', '_gcd_until', 'executor'),
    ('Executor no longer soft-gates on World.gcd_remaining', 'if World and World.gcd_remaining then', 'executor'),
    ('World still exposes public gcd_remaining (used elsewhere)', 'World.gcd_remaining = gcd_remaining', 'core/World.lua', 'utf-8'),
    ('World felfury tries explicit UnitPower index', 'unit_power_indices', 'world_src'),
    ('World felfury has aura-stack fallback', 'aura_names', 'world_src'),
    ('World stores _last_ctx for diagnostics', 'World._last_ctx = ctx', 'world_src'),
    ('Editor callbacks re-fetch rotation at fire time (>=4 sites)', 'editor_refetch_sites', 4),
    ('Farming.lua uses local found_unit', 'local found_unit', 'farming'),
    ('Farming.lua returns found_unit', 'return found_unit', 'farming'),
    ('RaijinLab.ADDON_VERSION single source', 'RaijinLab.ADDON_VERSION = "1.7.1"', 'variables'),
    ('TOC version bumped to 1.7', '## Version: 1.7', 'toc'),
    ('runtime OM default-on (Dispatch OmEnabled)', 'RL::Config::Get("om.enable", "1")', 'dispatch'),
    ('runtime OM probe diagnostic present', 'OM PROBE', 'runtime/src/game/ObjectManager.cpp', 'utf-8'),
    ('ChatHandler /raijin om arms om.probe', 'RaijinLab:RuntimeCall("SetSystemVar", "om.probe", "1")', 'chathandler'),
    ('DisableCTM.lua ships', 'core/DisableCTM.lua'),
]
